// <auto-generated />
namespace Icm.TaskManager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TaskDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201311172350185_TaskDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
