// <auto-generated />
namespace Icm.TaskManager.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Recurrences : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Recurrences));
        
        string IMigrationMetadata.Id
        {
            get { return "201312122111001_Recurrences"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
